<?php

namespace UserBundle\Entity;

/**
 * UserListenToAudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserListenToAudioRepository extends \Doctrine\ORM\EntityRepository
{
}
